### ISSUE TITLE
The autocomplete text doesn't appear on the same line

### ISSUE THREAD

**Issue by norassystemes** [norassystemes/terminal-react#4]
only for people that don't `reset styles` with tailwind

workaround
```css
p {
 margin:: 0;
}
```
add this to your project
