### ISSUE TITLE
The Icons on header buttons moves down

### ISSUE THREAD

**Issue by norassystemes** [norassystemes/terminal-react#5]
only for people that don't `reset styles` with tailwind

workaround
```css
svg {
  display: block;
  vertical-align: middle;
}
```
add this to your project
